project_id = "ehznqzaumsnjkrntaiox"

[functions.auth-me]
verify_jwt = true

[functions.users]
verify_jwt = true

[functions.menu]
verify_jwt = true

[functions.permissions]
verify_jwt = true

[functions.r2-upload]
verify_jwt = true

[functions.r2-view]
verify_jwt = true

[functions.r2-delete]
verify_jwt = true

[functions.r2-presign]
verify_jwt = true

[functions.create-image-row]
verify_jwt = false

[functions.r2-upload-url]
verify_jwt = true